baseURL = "https://jaynayai777-dev.github.io/TheAntilleanToday/"
title = "The Antillean Today"
languageCode = "en-us"
theme = "newsroom"

defaultContentLanguage = "en"

enableGitInfo = true
enableEmoji = true

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
[[module.imports]]
  path = "github.com/onweru/newsroom"
